"use strict";
(()=>{
  const c=game,x=c.getContext("2d"),N=8,S=65,O=70;let cur,ships,occupied,shots,score,state,sunk,mission,sonar,pings;
  function placeFleet(){ships=[];occupied=new Map();for(const length of[4,3,3,2]){let cells;do{const horizontal=Math.random()<.5,q=Math.floor(Math.random()*(horizontal?N-length+1:N)),r=Math.floor(Math.random()*(horizontal?N:N-length+1));cells=Array.from({length},(_,i)=>(r+(horizontal?0:i))*N+q+(horizontal?i:0))}while(cells.some(i=>occupied.has(i)));const ship={cells,hits:new Set(),sunk:false};ships.push(ship);cells.forEach(i=>occupied.set(i,ship))}}
  function operation(){cur=0;shots=new Map();state="play";sunk=0;sonar=Math.max(1,4-Math.floor(mission/2));pings=new Map();placeFleet();draw()}
  function reset(){score=0;mission=1;operation();StarcadeHost.score(0)}
  function fire(){if(state==="won"){mission++;operation();return}if(state==="complete"){reset();return}if(state!=="play"||shots.has(cur))return;const ship=occupied.get(cur);if(ship){ship.hits.add(cur);shots.set(cur,true);score+=200*mission;if(ship.hits.size===ship.cells.length){ship.sunk=true;sunk++;score+=500*mission;ship.cells.forEach(i=>shots.set(i,true))}}else{shots.set(cur,false);score=Math.max(0,score-25*mission)}StarcadeHost.score(score);if(ships.every(s=>s.sunk)){score+=Math.max(0,2500*mission-shots.size*25);StarcadeHost.score(score);if(mission>=5){state="complete";StarcadeHost.achievement("fleet-five-operations");StarcadeHost.finish(score)}else state="won"}draw()}
  function scan(){if(state!=="play"||sonar<=0)return;sonar--;for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){const q=cur%N+z,r=(cur>>3)+y;if(q>=0&&q<N&&r>=0&&r<N){const i=r*N+q;pings.set(i,occupied.has(i)?"contact":"clear")}}score=Math.max(0,score-100*mission);StarcadeHost.score(score);draw()}
  function draw(){x.fillStyle="#05090d";x.fillRect(0,0,660,660);for(let i=0;i<64;i++){const q=i%N,r=i>>3,px=O+q*S,py=O+r*S;x.fillStyle=shots.has(i)?shots.get(i)?"#ff8d72":"#152824":pings.get(i)==="contact"?"#453b20":pings.get(i)==="clear"?"#10211e":"#0c1715";x.fillRect(px,py,S-5,S-5);x.strokeStyle=i===cur?"#fff":"#31504a";x.lineWidth=i===cur?3:1;x.strokeRect(px,py,S-5,S-5);if(pings.get(i)==="contact"&&!shots.has(i)){x.strokeStyle="#f2c879";x.beginPath();x.arc(px+30,py+30,12,0,Math.PI*2);x.stroke()}if(shots.get(i)&&occupied.get(i)?.sunk){x.fillStyle="#f2c879";x.beginPath();x.arc(px+30,py+30,7,0,Math.PI*2);x.fill()}}x.fillStyle="#8df7c7";x.font="14px Arial";x.textAlign="left";x.fillText(`OP ${mission}/5  FLEETS ${sunk}/4  SHOTS ${shots.size}  SONAR ${sonar}  SCORE ${score}`,O,40);if(state==="won"||state==="complete"){x.fillStyle="rgba(3,7,6,.88)";x.fillRect(0,270,660,120);x.textAlign="center";x.fillStyle="#8df7c7";x.font="bold 27px Arial";x.fillText(state==="complete"?"SECTOR CAMPAIGN COMPLETE":"HOSTILE FLEET DESTROYED",330,315);x.fillStyle="#fff";x.font="14px Arial";x.fillText(state==="complete"?"A / ENTER: NEW CAMPAIGN":"A / ENTER: NEXT OPERATION",330,350);if(state==="complete")x.fillText(`FINAL SCORE ${score}`,330,375)}}
  addEventListener("keydown",e=>{const k=StarcadeInput.key(e),q=cur%N,r=cur>>3;if(k==="ArrowLeft")cur=r*N+(q+7)%N;if(k==="ArrowRight")cur=r*N+(q+1)%N;if(k==="ArrowUp")cur=((r+7)%N)*N+q;if(k==="ArrowDown")cur=((r+1)%N)*N+q;if(k==="Action")fire();if(k.toLowerCase()==="x")scan();if(StarcadeInput.isControl(k)||k.toLowerCase()==="x")e.preventDefault();draw()});reset();StarcadeHost.ready({title:"Fleet Command"});
})();
