"use strict";
(function(){
  const c=document.getElementById("game"),x=c.getContext("2d"),keys=new Set();let ship,rocks,shots,score,alive,lastShot,wave,lives,invulnerable,finished,waveDelay;
  const wrap=o=>{o.x=(o.x+c.width)%c.width;o.y=(o.y+c.height)%c.height};
  function rock(px,py,r){const speed=1+.08*wave;let q;do{q={x:px??Math.random()*c.width,y:py??Math.random()*c.height}}while(px==null&&Math.hypot(q.x-c.width/2,q.y-c.height/2)<150);return{...q,vx:(Math.random()-.5)*1.8*speed,vy:(Math.random()-.5)*1.8*speed,r:r||30+Math.random()*28,a:Math.random()*6.28}}
  function deploy(){ship={x:c.width/2,y:c.height/2,vx:0,vy:0,a:-Math.PI/2};invulnerable=150}
  function startWave(){rocks=Array.from({length:Math.min(5+wave,14)},()=>rock());shots=[];waveDelay=0;deploy()}
  function reset(){score=0;wave=1;lives=3;alive=true;finished=false;lastShot=0;startWave();StarcadeHost.score(0)}
  function hit(a,b){const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<(a.r+b.r)*(a.r+b.r)}
  function update(t){if(!alive)return;if(waveDelay){if(--waveDelay===0){wave++;score+=500*wave;StarcadeHost.score(score);startWave()}return}if(invulnerable>0)invulnerable--;if(keys.has("ArrowLeft"))ship.a-=.055;if(keys.has("ArrowRight"))ship.a+=.055;if(keys.has("ArrowUp")){ship.vx+=Math.cos(ship.a)*.075;ship.vy+=Math.sin(ship.a)*.075}if(keys.has("ArrowDown")){ship.vx*=.97;ship.vy*=.97}ship.vx*=.993;ship.vy*=.993;ship.x+=ship.vx;ship.y+=ship.vy;wrap(ship);if(keys.has("Space")&&t-lastShot>Math.max(95,180-wave*5)){shots.push({x:ship.x,y:ship.y,vx:ship.vx+Math.cos(ship.a)*6.5,vy:ship.vy+Math.sin(ship.a)*6.5,r:2,life:90});lastShot=t}shots.forEach(s=>{s.x+=s.vx;s.y+=s.vy;s.life--;wrap(s)});shots=shots.filter(s=>s.life>0);rocks.forEach(r=>{r.x+=r.vx;r.y+=r.vy;r.a+=.006;wrap(r)});for(let i=rocks.length-1;i>=0;i--)for(let j=shots.length-1;j>=0;j--)if(hit(rocks[i],shots[j])){const r=rocks[i];rocks.splice(i,1);shots.splice(j,1);score+=Math.round(1500/r.r)*wave;StarcadeHost.score(score);if(r.r>22)rocks.push(rock(r.x,r.y,r.r*.58),rock(r.x,r.y,r.r*.58));break}if(invulnerable<=0&&rocks.some(r=>hit({...ship,r:10},r))){lives--;if(lives<=0){alive=false;if(!finished){finished=true;StarcadeHost.finish(score)}}else deploy()}if(!rocks.length&&!waveDelay){waveDelay=90;if(wave===5)StarcadeHost.achievement("meteor-veteran")}}
  function drawShip(){if(invulnerable>0&&Math.floor(invulnerable/6)%2)return;x.save();x.translate(ship.x,ship.y);x.rotate(ship.a);x.strokeStyle="#8df7c7";x.lineWidth=2;x.beginPath();x.moveTo(15,0);x.lineTo(-11,-9);x.lineTo(-6,0);x.lineTo(-11,9);x.closePath();x.stroke();if(keys.has("ArrowUp")){x.strokeStyle="#f2c879";x.beginPath();x.moveTo(-7,-5);x.lineTo(-18,0);x.lineTo(-7,5);x.stroke()}x.restore()}
  function draw(){x.fillStyle="#050b0a";x.fillRect(0,0,c.width,c.height);x.fillStyle="#18312c";for(let i=0;i<80;i++)x.fillRect((i*131)%c.width,(i*79)%c.height,1,1);rocks.forEach(r=>{x.strokeStyle="#7d9b95";x.lineWidth=2;x.beginPath();for(let i=0;i<9;i++){const a=i/8*Math.PI*2+r.a,rr=r.r*(.82+.18*Math.sin(i*9.3));const px=r.x+Math.cos(a)*rr,py=r.y+Math.sin(a)*rr;i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()});x.fillStyle="#f2c879";shots.forEach(s=>x.fillRect(s.x-2,s.y-2,4,4));drawShip();x.fillStyle="#c8d8d2";x.font="15px Arial";x.textAlign="left";x.fillText(`WAVE ${wave}   HULL ${lives}   SCORE ${score}`,18,28);if(waveDelay){x.textAlign="center";x.fillStyle="#8df7c7";x.font="24px Arial";x.fillText(`SECTOR ${wave} CLEARED`,c.width/2,c.height/2)}if(!alive){x.fillStyle="rgba(2,7,6,.8)";x.fillRect(0,0,c.width,c.height);x.fillStyle="#e8f4f2";x.textAlign="center";x.font="30px Arial";x.fillText("HULL INTEGRITY LOST",c.width/2,c.height/2-10);x.fillStyle="#8df7c7";x.font="15px Arial";x.fillText("PRESS ENTER TO REDEPLOY",c.width/2,c.height/2+28)}}
  function loop(t){update(t);draw();requestAnimationFrame(loop)}
  function controlKey(e){const k=StarcadeInput.key(e);return k==="Action"?"Space":k}
  addEventListener("keydown",e=>{const key=controlKey(e);keys.add(key);if(["ArrowLeft","ArrowRight","ArrowUp","ArrowDown","Space"].includes(key))e.preventDefault();if(StarcadeInput.key(e)==="Action"&&!alive)reset()});addEventListener("keyup",e=>keys.delete(controlKey(e)));reset();StarcadeHost.ready({title:"Meteor Field"});requestAnimationFrame(loop);
})();
