"use strict";
(()=>{
  const c=game,x=c.getContext("2d"),symbols=["△","○","◇","✦","⌁","⬡","⊕","☄","✚","⌂","☾","⚙"];
  let cards,cursor,opened,score,lock,level,moves,state,cols,rows,started;
  const shuffle=a=>{for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
  function build(){const pairs=Math.min(12,6+level*2),chosen=shuffle([...symbols]).slice(0,pairs);cards=shuffle([...chosen,...chosen]).map(v=>({v,done:false,up:false}));cols=pairs<=8?4:6;rows=Math.ceil(cards.length/cols);cursor=0;opened=[];moves=0;lock=true;state="preview";started=performance.now();setTimeout(()=>{lock=false;state="play";cards.forEach(v=>v.up=false);draw()},Math.max(900,2300-level*180));cards.forEach(v=>v.up=true);draw()}
  function reset(){score=0;level=1;StarcadeHost.score(0);build()}
  function choose(){if(state==="complete"){reset();return}if(lock||cards[cursor].done||cards[cursor].up)return;cards[cursor].up=true;opened.push(cursor);if(opened.length===2){moves++;const[a,b]=opened;if(cards[a].v===cards[b].v){cards[a].done=cards[b].done=true;score+=Math.max(60,260-level*10-moves*2);StarcadeHost.score(score);opened=[];if(cards.every(v=>v.done)){state="level";lock=true;score+=Math.max(250,1500-Math.floor((performance.now()-started)/20));StarcadeHost.score(score);if(level===5){state="complete";lock=false;StarcadeHost.achievement("memory-matrix-master");StarcadeHost.finish(score)}else setTimeout(()=>{level++;build()},850)}}else{lock=true;setTimeout(()=>{cards[a].up=cards[b].up=false;opened=[];lock=false;draw()},Math.max(380,720-level*45))}}draw()}
  function draw(){x.fillStyle="#070c0b";x.fillRect(0,0,760,560);const gap=12,w=Math.min(112,(690-(cols-1)*gap)/cols),h=Math.min(88,(450-(rows-1)*gap)/rows),ox=(760-(cols*w+(cols-1)*gap))/2,oy=62;cards.forEach((d,i)=>{const q=i%cols,r=Math.floor(i/cols),px=ox+q*(w+gap),py=oy+r*(h+gap);x.fillStyle=d.done?"#24463d":d.up?"#ff9fc8":"#172522";x.fillRect(px,py,w,h);x.strokeStyle=i===cursor?"#fff":"#38504a";x.lineWidth=i===cursor?4:1;x.strokeRect(px,py,w,h);if(d.up||d.done){x.textAlign="center";x.textBaseline="middle";x.fillStyle=d.done?"#8df7c7":"#111";x.font=`${Math.min(38,h*.48)}px Arial`;x.fillText(d.v,px+w/2,py+h/2)}});x.textBaseline="alphabetic";x.textAlign="center";x.font="15px Arial";x.fillStyle="#a9bbb7";x.fillText(`LEVEL ${level}/5   MOVES ${moves}   SCORE ${score}${state==="preview"?"   ·   MEMORIZE":state==="level"?"   ·   MATRIX CLEARED":""}`,380,30);if(state==="complete"){x.fillStyle="rgba(3,7,6,.9)";x.fillRect(0,220,760,120);x.fillStyle="#8df7c7";x.font="bold 26px Arial";x.fillText("MEMORY MATRIX MASTERED",380,270);x.fillStyle="#fff";x.font="14px Arial";x.fillText("PRESS A / ENTER TO RESTART",380,305)}}
  addEventListener("keydown",e=>{const k=StarcadeInput.key(e),q=cursor%cols,r=Math.floor(cursor/cols);if(k==="ArrowLeft")cursor=r*cols+(q+cols-1)%cols;if(k==="ArrowRight")cursor=r*cols+(q+1)%cols;if(k==="ArrowUp")cursor=((r+rows-1)%rows)*cols+q;if(k==="ArrowDown")cursor=((r+1)%rows)*cols+q;cursor=Math.min(cards.length-1,cursor);if(k==="Action")choose();if(StarcadeInput.isControl(k)){e.preventDefault();draw()}});reset();StarcadeHost.ready({title:"Memory Matrix"});
})();
