"use strict";
(()=>{const c=game,x=c.getContext("2d"),keys=new Set();let ship,shots,enemyShots,foes,shields,dir,score,alive,cool,wave,lives,enemyCool,finished,invulnerable;
function formation(){foes=[];for(let r=0;r<5;r++)for(let q=0;q<10;q++)foes.push({x:155+q*62,y:65+r*46,on:true,type:r===0?2:r<3?1:0,col:q});dir=1;enemyShots=[];shots=[];enemyCool=80}
function reset(){ship=450;score=0;wave=1;lives=3;alive=true;cool=0;finished=false;invulnerable=0;shields=[180,360,540,720].map(q=>({x:q,hp:6}));formation();StarcadeHost.score(0)}
function loseLife(){if(invulnerable>0)return;lives--;invulnerable=1;setTimeout(()=>invulnerable=0,1200);enemyShots=[];ship=450;if(lives<=0){alive=false;if(!finished){finished=true;StarcadeHost.finish(score)}}}
function fireEnemy(){const columns=[];for(let q=0;q<10;q++){const live=foes.filter(f=>f.on&&f.col===q).sort((a,b)=>b.y-a.y);if(live[0])columns.push(live[0])}if(columns.length){const f=columns[Math.floor(Math.random()*columns.length)];enemyShots.push({x:f.x,y:f.y+15,v:3+wave*.18})}}
function step(){if(alive){if(keys.has("ArrowLeft"))ship-=6;if(keys.has("ArrowRight"))ship+=6;ship=Math.max(28,Math.min(872,ship));if(keys.has("Action")&&cool<=0){shots.push({x:ship,y:500});cool=Math.max(7,14-Math.floor(wave/3))}cool--;shots.forEach(s=>s.y-=9);enemyShots.forEach(s=>s.y+=s.v);shots=shots.filter(s=>s.y>-10);enemyShots=enemyShots.filter(s=>s.y<570);if(--enemyCool<=0){fireEnemy();enemyCool=Math.max(18,75-wave*4)}let edge=false;const speed=.42+wave*.07;foes.forEach(f=>{if(f.on){f.x+=dir*speed;if(f.x<35||f.x>865)edge=true}});if(edge){dir*=-1;foes.forEach(f=>f.y+=12+wave)}for(const s of shots)for(const f of foes)if(f.on&&Math.abs(s.x-f.x)<22&&Math.abs(s.y-f.y)<17){f.on=false;s.y=-20;score+=(f.type+1)*100*wave;StarcadeHost.score(score);break}for(const s of enemyShots){for(const h of shields)if(h.hp>0&&Math.abs(s.x-h.x)<50&&s.y>435&&s.y<475){h.hp--;s.y=600;break}if(s.y>485&&Math.abs(s.x-ship)<27){s.y=600;loseLife()}}for(const s of shots)for(const z of enemyShots)if(Math.abs(s.x-z.x)<8&&Math.abs(s.y-z.y)<12){s.y=-20;z.y=600;score+=25}if(foes.some(f=>f.on&&f.y>445)){lives=0;loseLife()}if(!foes.some(f=>f.on)){wave++;score+=1000*wave;StarcadeHost.score(score);if(wave===5)StarcadeHost.achievement("invaders-sector-five");formation()}}draw();requestAnimationFrame(step)}
function draw(){x.fillStyle="#05090d";x.fillRect(0,0,900,560);x.fillStyle="#8df7c7";foes.forEach(f=>{if(f.on){x.fillStyle=f.type===2?"#f2c879":f.type===1?"#8df7c7":"#7dc7ff";x.fillRect(f.x-18,f.y-10,36,20);x.fillRect(f.x-25,f.y-3,8,12);x.fillRect(f.x+17,f.y-3,8,12)}});shields.forEach(h=>{if(h.hp){x.fillStyle=`rgba(141,247,199,${.2+h.hp*.1})`;x.fillRect(h.x-48,445,96,22)}});x.fillStyle="#f2c879";shots.forEach(s=>x.fillRect(s.x-2,s.y-9,4,12));x.fillStyle="#ff8d72";enemyShots.forEach(s=>x.fillRect(s.x-2,s.y,4,12));x.fillStyle="#7dc7ff";x.beginPath();x.moveTo(ship,490);x.lineTo(ship-24,520);x.lineTo(ship+24,520);x.fill();x.fillStyle="#c8d8d2";x.font="15px Arial";x.textAlign="left";x.fillText(`WAVE ${wave}   SHIPS ${lives}   SCORE ${score}`,18,28);if(!alive){x.fillStyle="rgba(3,7,6,.88)";x.fillRect(0,220,900,120);x.textAlign="center";x.fillStyle="#ff8d72";x.font="28px Arial";x.fillText("SECTOR OVERRUN",450,270);x.fillStyle="#fff";x.font="14px Arial";x.fillText("PRESS A / ENTER TO RESTART",450,305)}}
addEventListener("keydown",e=>{const k=StarcadeInput.key(e);keys.add(k);if(k==="Action"&&!alive)reset();if(StarcadeInput.isControl(k))e.preventDefault()});addEventListener("keyup",e=>keys.delete(StarcadeInput.key(e)));reset();StarcadeHost.ready({title:"Void Invaders"});requestAnimationFrame(step)})();
