"use strict";
(()=>{const c=game,x=c.getContext("2d"),keys=new Set();let ship,dock,score,time,state,mission,fuel,streak;
const tolerance=()=>({align:Math.max(18,42-mission*2),speed:Math.max(.58,1.45-mission*.07)});
function contract(){ship={x:95,y:100+Math.random()*360,vx:0,vy:0};dock={x:780,y:280,phase:Math.random()*6,rate:.012+mission*.0015};time=Math.max(2100,3900-mission*120);fuel=Math.max(360,720-mission*25);state="fly"}
function reset(){score=0;mission=1;streak=0;contract();StarcadeHost.score(0)}
function end(ok){state=ok?"docked":"failed";if(ok){streak++;const speed=Math.hypot(ship.vx,ship.vy),bonus=Math.floor(time*.6+fuel*3+(tolerance().speed-speed)*900);score+=Math.max(250,bonus)*mission;StarcadeHost.score(score);if(mission===5)StarcadeHost.achievement("docking-five-contracts")}else{streak=0;StarcadeHost.finish(score)}}
function step(){if(state==="fly"){let burn=false;if(keys.has("ArrowLeft")&&fuel){ship.vx-=.018;burn=true}if(keys.has("ArrowRight")&&fuel){ship.vx+=.018;burn=true}if(keys.has("ArrowUp")&&fuel){ship.vy-=.018;burn=true}if(keys.has("ArrowDown")&&fuel){ship.vy+=.018;burn=true}if(burn)fuel=Math.max(0,fuel-1);ship.vx*=.994;ship.vy*=.994;ship.x+=ship.vx;ship.y+=ship.vy;dock.phase+=dock.rate;dock.y=280+Math.sin(dock.phase)*Math.min(190,110+mission*8);time--;if(ship.x>742){const d=Math.abs(ship.y-dock.y),speed=Math.hypot(ship.vx,ship.vy),t=tolerance();end(d<t.align&&speed<t.speed)}else if(ship.x<10||ship.y<10||ship.y>550||time<=0)end(false)}draw();requestAnimationFrame(step)}
function draw(){x.fillStyle="#05090d";x.fillRect(0,0,900,560);x.strokeStyle="#17312c";for(let i=0;i<30;i++){const q=(i*83+time*.12)%900;x.beginPath();x.moveTo(q,0);x.lineTo(q-80,560);x.stroke()}const t=tolerance();x.fillStyle="rgba(141,247,199,.08)";x.fillRect(742,dock.y-t.align,70,t.align*2);x.strokeStyle="#8df7c7";x.lineWidth=5;x.strokeRect(770,dock.y-48,32,96);x.save();x.translate(ship.x,ship.y);x.fillStyle="#7dc7ff";x.fillRect(-18,-11,36,22);x.strokeStyle="#fff";x.strokeRect(-18,-11,36,22);x.restore();x.fillStyle="#9fb2ae";x.font="14px Arial";x.textAlign="left";x.fillText(`CONTRACT ${mission}  RANGE ${Math.max(0,Math.floor(dock.x-ship.x))}  SPEED ${Math.hypot(ship.vx,ship.vy).toFixed(2)}/${t.speed.toFixed(2)}  FUEL ${fuel}  TIME ${Math.ceil(time/60)}`,18,28);x.fillText(`ALIGNMENT ${Math.round(Math.abs(ship.y-dock.y))}/${t.align}   STREAK ${streak}   SCORE ${score}`,18,52);if(state!=="fly"){x.fillStyle="rgba(3,7,6,.88)";x.fillRect(0,220,900,130);x.textAlign="center";x.fillStyle=state==="docked"?"#8df7c7":"#ff8d72";x.font="28px Arial";x.fillText(state==="docked"?"DOCKING COMPLETE":"VECTOR LOST",450,268);x.font="14px Arial";x.fillText(state==="docked"?"A / ENTER: ACCEPT HARDER CONTRACT":"A / ENTER: NEW OPERATION",450,306)}}
addEventListener("keydown",e=>{const k=StarcadeInput.key(e);keys.add(k);if(k==="Action"&&state!=="fly"){if(state==="docked"){mission++;contract()}else reset()}if(StarcadeInput.isControl(k))e.preventDefault()});addEventListener("keyup",e=>keys.delete(StarcadeInput.key(e)));reset();StarcadeHost.ready({title:"Docking Vector"});requestAnimationFrame(step)})();
