"use strict";
(() => {
  const c=document.getElementById("game"),x=c.getContext("2d"),W=10,H=20,S=30,O=110;
  const shapes=[[[1,1,1,1]],[[1,1],[1,1]],[[0,1,0],[1,1,1]],[[1,0,0],[1,1,1]],[[0,0,1],[1,1,1]],[[0,1,1],[1,1,0]],[[1,1,0],[0,1,1]]];
  const colors=["#7dc7ff","#f2c879","#c58cff","#ff9fc8","#ff8d72","#8df7c7","#86a8ff"];
  let board,p,nextQueue,held=null,canHold=true,last=0,score=0,lines=0,level=1,combo=-1,backToBack=false,over=false,paused=false,finished=false,bag=[],lockSince=0,lockResets=0,lastAction="",lastClear="",surge="CALIBRATION";
  const phases=["CALIBRATION","ORBITAL DRIFT","SOLAR PRESSURE","GRAVITY SHEAR","STARFALL CORE"];

  function clone(m){return m.map(r=>r.slice())}
  function randomPiece(){if(!bag.length){bag=[0,1,2,3,4,5,6];for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]]}}const i=bag.pop();return{x:3,y:0,m:clone(shapes[i]),color:colors[i],id:i,rot:0}}
  function canonical(id){return{x:3,y:0,m:clone(shapes[id]),color:colors[id],id,rot:0}}
  function fillQueue(){while(nextQueue.length<5)nextQueue.push(randomPiece())}
  function spawn(){fillQueue();p=nextQueue.shift();fillQueue();p.x=3;p.y=0;canHold=true;lockSince=0;lockResets=0;lastAction="spawn";if(hit())gameOver()}
  function hit(q=p,dx=0,dy=0,m=q.m){return m.some((r,y)=>r.some((v,z)=>v&&(q.x+z+dx<0||q.x+z+dx>=W||q.y+y+dy>=H||q.y+y+dy>=0&&board[q.y+y+dy][q.x+z+dx])))}
  function fallDelay(){return Math.max(70,Math.round(700*Math.pow(.84,level-1)))}
  function rotate(){const m=p.m[0].map((_,i)=>p.m.map(r=>r[i]).reverse()),to=(p.rot+1)%4;for(const[dx,dy]of[[0,0],[-1,0],[1,0],[-2,0],[2,0],[0,-1],[-1,-1],[1,-1],[0,-2]])if(!hit(p,dx,dy,m)){p.x+=dx;p.y+=dy;p.m=m;p.rot=to;lastAction="rotate";if(lockSince&&lockResets<15){lockSince=performance.now();lockResets++}return}}
  function ghostY(){let y=p.y;while(!hit({...p,y},0,1))y++;return y}
  function tSpin(){if(p.id!==2||lastAction!=="rotate")return false;const cx=p.x+1,cy=p.y+1;let blocked=0;for(const[dx,dy]of[[-1,-1],[1,-1],[-1,1],[1,1]]){const q=cx+dx,r=cy+dy;if(q<0||q>=W||r<0||r>=H||board[r][q])blocked++}return blocked>=3}
  function addPressureRow(){if(board[0].some(Boolean))return false;const hole=Math.floor(Math.random()*W),row=Array.from({length:W},(_,i)=>i===hole?0:"#5c6764");board.shift();board.push(row);lastClear="GRAVITY SURGE";score+=250*level;return true}
  function advanceLevel(oldLevel){surge=phases[Math.min(phases.length-1,Math.floor((level-1)/3))];if(level>oldLevel){score+=level*100;if(level%5===0)addPressureRow();if([5,10,15].includes(level))StarcadeHost.achievement(`starfall-level-${level}`)}}
  function lock(){const spin=tSpin();p.m.forEach((r,y)=>r.forEach((v,z)=>{if(v&&p.y+y>=0)board[p.y+y][p.x+z]=p.color}));let cleared=0;board=board.filter(r=>{if(r.every(Boolean)){cleared++;return false}return true});while(board.length<H)board.unshift(Array(W).fill(0));
    if(cleared||spin){combo++;const difficult=cleared===4||spin&&cleared>0;const normal=[0,100,300,500,800][cleared];const spinValue=spin?[400,800,1200,1600][cleared]:0;const base=Math.max(normal,spinValue)*level;const b2b=difficult&&backToBack?Math.floor(base*.5):0;const chain=combo>0?combo*50*level:0,oldLevel=level;score+=base+b2b+chain;lines+=cleared;level=Math.floor(lines/10)+1;backToBack=difficult;lastClear=spin?`T-SPIN${cleared?` ${cleared} LINE`:""}`:["","SINGLE","DOUBLE","TRIPLE","STARFALL"][cleared];const perfect=board.every(r=>r.every(v=>!v));if(perfect){score+=3500*level;lastClear="PERFECT CLEAR";StarcadeHost.achievement("starfall-perfect-clear")}if(spin)StarcadeHost.achievement("starfall-t-spin");advanceLevel(oldLevel);StarcadeHost.score(score)}else{combo=-1;lastClear=""}
    spawn();last=performance.now();
  }
  function drop(){let cells=0;while(!hit(p,0,1)){p.y++;cells++}score+=cells*2;lock();StarcadeHost.score(score)}
  function hold(){if(!canHold)return;const oldId=p.id;if(held!==null){p=canonical(held);held=oldId}else{held=oldId;fillQueue();p=nextQueue.shift();fillQueue();p.x=3;p.y=0}canHold=false;lockSince=0;lockResets=0;lastAction="hold";if(hit())gameOver()}
  function gameOver(){over=true;if(!finished){finished=true;StarcadeHost.finish(score)}}
  function reset(){board=Array.from({length:H},()=>Array(W).fill(0));bag=[];nextQueue=[];held=null;score=0;lines=0;level=1;combo=-1;backToBack=false;over=false;paused=false;finished=false;last=0;lockSince=0;lastClear="";surge=phases[0];spawn();StarcadeHost.score(0)}
  function step(t){if(!over&&!paused){if(hit(p,0,1)){if(!lockSince)lockSince=t;if(t-lockSince>=500)lock()}else{lockSince=0;if(t-last>fallDelay()){p.y++;last=t}}}draw();requestAnimationFrame(step)}
  function cell(q,r,col,alpha=1){x.globalAlpha=alpha;x.fillStyle=col;x.fillRect(O+q*S+1,31+r*S,S-2,S-2);x.strokeStyle="rgba(255,255,255,.13)";x.strokeRect(O+q*S+2,32+r*S,S-4,S-4);x.globalAlpha=1}
  function mini(piece,ox,oy,scale=16){if(piece===null||piece===undefined)return;const q=typeof piece==="number"?canonical(piece):piece;q.m.forEach((r,y)=>r.forEach((v,z)=>{if(v){x.fillStyle=q.color;x.fillRect(ox+z*scale,oy+y*scale,scale-2,scale-2)}}))}
  function draw(){x.fillStyle="#050908";x.fillRect(0,0,c.width,c.height);x.strokeStyle="#152923";for(let i=0;i<=W;i++){x.beginPath();x.moveTo(O+i*S,30);x.lineTo(O+i*S,630);x.stroke()}for(let i=0;i<=H;i++){x.beginPath();x.moveTo(O,30+i*S);x.lineTo(O+W*S,30+i*S);x.stroke()}for(let y=0;y<H;y++)for(let z=0;z<W;z++)if(board[y][z])cell(z,y,board[y][z]);
    if(!over){const gy=ghostY();p.m.forEach((r,y)=>r.forEach((v,z)=>{if(v){cell(p.x+z,gy+y,p.color,.2);cell(p.x+z,p.y+y,p.color)}}))}
    x.fillStyle="#829792";x.font="12px Arial";x.fillText("SCORE",12,45);x.fillStyle="#e8f4f2";x.font="18px Arial";x.fillText(String(score),12,68);x.fillStyle="#829792";x.font="12px Arial";x.fillText(`LEVEL ${level}`,12,105);x.fillText(`LINES ${lines}`,12,127);x.fillStyle="#8df7c7";x.font="10px Arial";x.fillText(surge,12,148);x.fillStyle="#829792";x.font="12px Arial";x.fillText("HOLD",12,178);mini(held,16,195);x.fillText("NEXT 5",426,45);nextQueue.forEach((q,i)=>mini(q,430,64+i*67,12));x.fillText(`${fallDelay()} MS`,426,420);x.fillText("7-BAG ACTIVE",426,444);x.fillText(level<5?`SURGE IN ${5-level} LEVELS`:`SURGE EVERY 5`,426,468);if(lockSince){x.fillStyle="#f2c879";x.fillText("LOCK DELAY",426,492)}if(combo>0){x.fillStyle="#f2c879";x.fillText(`COMBO x${combo+1}`,12,290)}if(backToBack){x.fillStyle="#8df7c7";x.fillText("BACK-TO-BACK",12,315)}if(lastClear){x.fillStyle="#f2c879";x.font="bold 12px Arial";x.fillText(lastClear,12,342)}
    if(over||paused){x.fillStyle="rgba(3,7,6,.86)";x.fillRect(O,270,300,115);x.textAlign="center";x.fillStyle=over?"#ff8d72":"#f2c879";x.font="24px Arial";x.fillText(over?"STACK COLLAPSE":"SYSTEM PAUSED",260,312);x.font="13px Arial";x.fillStyle="#e8f4f2";x.fillText(over?"PRESS ENTER TO RESTART":"PRESS P TO CONTINUE",260,344);x.textAlign="left"}}
  addEventListener("keydown",e=>{const k=StarcadeInput.key(e),grounded=hit(p,0,1);if(k.toLowerCase()==="p"&&!over){paused=!paused;last=performance.now();e.preventDefault();return}if(over){if(k==="Action")reset();return}if(paused)return;if(k==="ArrowLeft"&&!hit(p,-1,0)){p.x--;lastAction="move";if(grounded&&lockResets<15){lockSince=performance.now();lockResets++}}else if(k==="ArrowRight"&&!hit(p,1,0)){p.x++;lastAction="move";if(grounded&&lockResets<15){lockSince=performance.now();lockResets++}}else if(k==="ArrowUp")rotate();else if(k==="ArrowDown"){if(hit(p,0,1)){if(lockSince&&performance.now()-lockSince>=500)lock()}else{p.y++;score++;lastAction="soft-drop";lockSince=0}}else if(k==="Action")drop();else if(k.toLowerCase()==="c"||k==="Shift")hold();if(StarcadeInput.isControl(k)||k.toLowerCase()==="c"||k==="Shift"){e.preventDefault();draw()}});
  reset();StarcadeHost.ready({title:"Starfall Blocks"});requestAnimationFrame(step);
})();
