"use strict";
(()=>{const $=id=>document.getElementById(id),suits=["♠","♥","♦","♣"],ranks=["A","2","3","4","5","6","7","8","9","10","J","Q","K"];let shoe=[],player=[],dealer=[],active=false,busy=false,stake=0,hands=0,wins=0,losses=0,pushes=0;
function shuffle(){shoe=[];for(let d=0;d<6;d++)for(const s of suits)for(const r of ranks)shoe.push({s,r});for(let i=shoe.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[shoe[i],shoe[j]]=[shoe[j],shoe[i]]}}
function draw(){if(shoe.length<78)shuffle();return shoe.pop()}function value(hand){let n=0,aces=0;for(const c of hand){if(c.r==='A'){n+=11;aces++}else n+=/[JQK]/.test(c.r)?10:+c.r}while(n>21&&aces){n-=10;aces--}return{total:n,soft:aces>0}}
function card(c,hidden=false){return`<div class="card ${hidden?'back':/[♥♦]/.test(c.s)?'red':''}">${hidden?'':`${c.r}<br>${c.s}`}</div>`}
function render(reveal=!active){$('player').innerHTML=player.map(c=>card(c)).join('');$('dealer').innerHTML=dealer.map((c,i)=>card(c,!reveal&&i===1)).join('');$('playerValue').textContent=player.length?`· ${value(player).total}`:'';$('dealerValue').textContent=dealer.length&&reveal?`· ${value(dealer).total}`:'';$('shoe').textContent=`SHOE ${shoe.length}/312 · HANDS ${hands} · W ${wins} L ${losses} P ${pushes}`}
function controls(on){active=on;$('hit').disabled=!on;$('stand').disabled=!on;$('surrender').disabled=!on||player.length!==2;$('deal').disabled=on||busy;$('wager').disabled=on||busy;render()}
async function settle(label,pay,outcome){busy=true;active=false;render(true);try{await CasinoBank.payout(pay);hands++;if(outcome==='win')wins++;else if(outcome==='loss')losses++;else pushes++;$('message').textContent=label+(pay?` · RETURN ${pay}`:'');$('balance').textContent=`CREDITS: ${CasinoBank.balance}`;StarcadeHost.score(Math.max(0,(wins-losses)*100));StarcadeHost.finish(Math.max(0,(wins-losses)*100))}catch(e){$('message').textContent=e.message}finally{busy=false;controls(false)}}
function resolve(){while(value(dealer).total<17)dealer.push(draw());const p=value(player).total,d=value(dealer).total;if(d>21||p>d)settle('PLAYER WINS',stake*2,'win');else if(p===d)settle('PUSH',stake,'push');else settle('DEALER WINS',0,'loss')}
async function deal(){if(active||busy)return;busy=true;controls(false);stake=+$('wager').value;$('message').textContent='AUTHORIZING WAGER';try{await CasinoBank.wager(stake);player=[draw(),draw()];dealer=[draw(),draw()];busy=false;controls(true);const p=value(player).total,d=value(dealer).total;if(p===21){if(d===21)settle('BLACKJACK PUSH',stake,'push');else settle('BLACKJACK · 3:2',Math.floor(stake*2.5),'win')}else $('message').textContent='HIT, STAND, OR EARLY SURRENDER'}catch(e){busy=false;$('message').textContent=e.message;controls(false)}}
$('deal').onclick=deal;$('hit').onclick=()=>{if(!active)return;player.push(draw());render();const v=value(player).total;if(v>21)settle('BUST · DEALER WINS',0,'loss');else if(v===21)resolve();else if(player.length>=5)settle('FIVE-CARD CHARLIE',stake*2,'win')};$('stand').onclick=()=>{if(active)resolve()};$('surrender').onclick=()=>{if(active&&player.length===2)settle('EARLY SURRENDER',Math.floor(stake/2),'loss')};shuffle();render();CasinoBank.refresh().then(()=>$('balance').textContent=`CREDITS: ${CasinoBank.balance}`).catch(e=>$('message').textContent=e.message);StarcadeHost.ready({title:'Red Mile Blackjack'})})();
