"use strict";
(()=>{
  const $=id=>document.getElementById(id),SUITS=["♠","♥","♦","♣"],NAMES=["2","3","4","5","6","7","8","9","10","J","Q","K","A"];
  const LABELS=["HIGH CARD","PAIR","TWO PAIR","THREE OF A KIND","STRAIGHT","FLUSH","FULL HOUSE","FOUR OF A KIND","STRAIGHT FLUSH"];
  let deck=[],player=[],cpu=[],board=[],street=0,stake=0,pot=0,pStack=0,cStack=0,toCall=0,busy=false,active=false,raises=0,dealer=false;
  function fresh(){deck=[];for(let s=0;s<4;s++)for(let v=2;v<=14;v++)deck.push({s,v});for(let i=deck.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}}
  function card(c,hidden=false){return `<div class="playing-card ${!hidden&&(c.s===1||c.s===2)?"red":""}">${hidden?"STARCADE":`${NAMES[c.v-2]}<br>${SUITS[c.s]}`}</div>`}
  function five(h){const v=h.map(c=>c.v).sort((a,b)=>b-a),groups=[...new Set(v)].map(n=>[v.filter(x=>x===n).length,n]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]),flush=h.every(c=>c.s===h[0].s),u=[...new Set(v)].sort((a,b)=>b-a);if(u[0]===14)u.push(1);let high=0;for(let i=0;i<=u.length-5;i++)if(u[i]-u[i+4]===4){high=u[i];break}if(flush&&high)return[8,high];if(groups[0][0]===4)return[7,groups[0][1],...v.filter(x=>x!==groups[0][1])];if(groups[0][0]===3&&groups[1]?.[0]>=2)return[6,groups[0][1],groups[1][1]];if(flush)return[5,...v];if(high)return[4,high];if(groups[0][0]===3)return[3,groups[0][1],...v.filter(x=>x!==groups[0][1])];if(groups[0][0]===2&&groups[1]?.[0]===2){const p=[groups[0][1],groups[1][1]].sort((a,b)=>b-a);return[2,...p,...v.filter(x=>!p.includes(x))]}if(groups[0][0]===2)return[1,groups[0][1],...v.filter(x=>x!==groups[0][1])];return[0,...v]}
  function rank7(h){if(h.length===5)return five(h);let best=null;const choose=(start,pick)=>{if(pick.length===5){const r=five(pick);if(!best||cmp(r,best)>0)best=r;return}for(let i=start;i<=h.length-(5-pick.length);i++)choose(i+1,[...pick,h[i]])};choose(0,[]);return best}
  function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
  function preflop(){const[a,b]=cpu,hi=Math.max(a.v,b.v),lo=Math.min(a.v,b.v);return Math.min(.92,.2+(a.v===b.v?.42:0)+(a.s===b.s?.08:0)+(hi/14)*.2+(hi-lo<=2?.08:0))}
  function equity(samples=90){if(board.length<3)return preflop();let wins=0,ties=0;const known=new Set([...cpu,...board].map(c=>`${c.s}:${c.v}`)),pool=[];for(let s=0;s<4;s++)for(let v=2;v<=14;v++)if(!known.has(`${s}:${v}`))pool.push({s,v});for(let n=0;n<samples;n++){const q=pool.slice();for(let i=q.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[q[i],q[j]]=[q[j],q[i]]}const foe=q.splice(0,2),run=[...board];while(run.length<5)run.push(q.pop());const z=cmp(rank7([...cpu,...run]),rank7([...foe,...run]));if(z>0)wins++;else if(!z)ties++}return(wins+ties*.5)/samples}
  function controls(on){active=on;$("check").disabled=!on;$("raise").disabled=!on||raises>=2||pStack<=toCall+1;$("fold").disabled=!on||toCall===0;$("deal").disabled=on;$("wager").disabled=on;$("check").textContent=toCall?`CALL ${toCall}`:"CHECK"}
  function render(reveal=false){$("player").innerHTML=player.map(c=>card(c)).join("");$("cpu").innerHTML=cpu.map(c=>card(c,!reveal)).join("");$("board").innerHTML=board.map(c=>card(c)).join("");$("pot").textContent=`POT: ${pot} CHIPS`;$("stacks").textContent=`YOU ${pStack} · CPU ${cStack}`;$("street").textContent=["WAITING FOR DEAL","PRE-FLOP","FLOP","TURN","RIVER","SHOWDOWN"][street];controls(active)}
  function payoutFromPot(){return Math.min(stake*3,Math.max(stake,Math.floor(stake*pot/10)))}
  async function settle(label,pay,reveal=true){busy=true;active=false;render(reveal);try{await CasinoBank.payout(pay);$("balance").textContent=`CREDITS: ${CasinoBank.balance}`;$("status").textContent=`${label}${pay?` · RETURN ${pay}`:""}`;StarcadeHost.finish(pay)}catch(e){$("status").textContent=e.message}finally{busy=false;$("deal").disabled=false;$("wager").disabled=false;$("deal").textContent="NEW HAND"}}
  function showdown(){street=5;const pr=rank7([...player,...board]),cr=rank7([...cpu,...board]),n=cmp(pr,cr);if(n>0)settle(`YOU WIN · ${LABELS[pr[0]]}`,payoutFromPot());else if(n<0)settle(`CPU WINS · ${LABELS[cr[0]]}`,0);else settle(`SPLIT POT · ${LABELS[pr[0]]}`,stake)}
  function revealStreet(){raises=0;toCall=0;if(street===1){board=deck.splice(0,3);street=2}else if(street===2){board.push(deck.pop());street=3}else if(street===3){board.push(deck.pop());street=4}else{showdown();return}active=true;cpuTurn()}
  function cpuTurn(){if(!active)return;const e=equity(),betSize=street>=3?2:1;if(cStack>=betSize&&e>.58&&Math.random()<.35+e*.35){cStack-=betSize;pot+=betSize;toCall=betSize;$("status").textContent=`CPU BETS ${betSize} · CALL, RAISE, OR FOLD`}else{$("status").textContent="CPU CHECKS · CHECK OR RAISE"}render()}
  function cpuRespondToRaise(amount){const e=equity(),price=amount/Math.max(1,pot);if(e+Math.random()*.22<price+.18){settle("CPU FOLDS · YOU TAKE THE POT",payoutFromPot(),false);return}const call=Math.min(amount,cStack);cStack-=call;pot+=call;$("status").textContent=e>.78&&raises<2?"CPU CALLS · STRONG RANGE":"CPU CALLS";setTimeout(revealStreet,420)}
  function act(kind){if(!active||busy)return;if(kind==="fold"){settle("YOU FOLD · CPU TAKES THE POT",0);return}if(kind==="raise"){const call=Math.min(toCall,pStack),raise=Math.min(street>=3?2:1,pStack-call);pStack-=call+raise;pot+=call+raise;toCall=0;raises++;active=false;render();$("status").textContent=`YOU RAISE ${raise}`;setTimeout(()=>cpuRespondToRaise(raise),350);return}if(toCall){const call=Math.min(toCall,pStack);pStack-=call;pot+=call;toCall=0;$("status").textContent=`YOU CALL ${call} · BETTING ROUND COMPLETE`}else $("status").textContent="BOTH PLAYERS CHECK";active=false;render();setTimeout(revealStreet,350)}
  async function openWager(){try{return await CasinoBank.wager(stake)}catch(e){if(!/wager is already active/i.test(e.message))throw e;$("status").textContent="RECOVERING INTERRUPTED HAND...";try{await CasinoBank.cancel()}catch(cancelError){if(!/cancellation queued/i.test(cancelError.message))throw e}return CasinoBank.wager(stake)}}
  $("deal").onclick=async()=>{if(busy||active)return;busy=true;stake=+$("wager").value;$("deal").disabled=true;try{await openWager();fresh();player=deck.splice(0,2);cpu=deck.splice(0,2);board=[];street=1;pot=20;pStack=cStack=10;toCall=dealer?1:0;if(toCall){cStack--;pot++;$("status").textContent="CPU POSTS · CALL, RAISE, OR FOLD"}else $("status").textContent="ACTION TO YOU · CHECK OR RAISE";dealer=!dealer;raises=0;active=true;$("deal").textContent="HAND ACTIVE";render()}catch(e){$("status").textContent=e.message;$("deal").disabled=false}finally{busy=false}};
  $("check").onclick=()=>act("check");$("raise").onclick=()=>act("raise");$("fold").onclick=()=>act("fold");render();CasinoBank.refresh().then(()=>$("balance").textContent=`CREDITS: ${CasinoBank.balance}`).catch(e=>$("status").textContent=e.message);StarcadeHost.ready({title:"Red Mile Hold 'Em"});
})();
