"use strict";
(()=>{
  const c=game,x=c.getContext("2d"),N=8,S=72,O=42;
  let cells,cursor,state,score,sector,first,started,elapsed;
  const neighbors=(i)=>{const q=i%N,r=i>>3,a=[];for(let y=-1;y<=1;y++)for(let z=-1;z<=1;z++){const xx=q+z,yy=r+y;if((z||y)&&xx>=0&&yy>=0&&xx<N&&yy<N)a.push(yy*N+xx)}return a};
  function blank(){cells=Array.from({length:N*N},()=>({mine:false,open:false,flag:false,n:0}));cursor=0;state="play";first=true;started=performance.now();elapsed=0;draw()}
  function reset(){score=0;sector=1;StarcadeHost.score(0);blank()}
  function generate(safe){const mines=Math.min(18,8+sector*2),blocked=new Set([safe,...neighbors(safe)]);let placed=0;while(placed<mines){const i=Math.floor(Math.random()*64);if(!blocked.has(i)&&!cells[i].mine){cells[i].mine=true;placed++}}cells.forEach((d,i)=>d.n=neighbors(i).filter(j=>cells[j].mine).length);first=false}
  function reveal(i){const d=cells[i];if(d.open||d.flag)return;if(first)generate(i);d.open=true;score+=10+sector*2;if(d.n===0)neighbors(i).forEach(reveal)}
  function complete(){return cells.every(d=>d.mine||d.open)}
  function finish(kind){state=kind;if(kind==="won"){const timeBonus=Math.max(0,1800-Math.floor(elapsed/50)),flagBonus=cells.filter(d=>d.flag&&d.mine).length*40;score+=1000*sector+timeBonus+flagBonus;StarcadeHost.score(score);if(sector===5)StarcadeHost.achievement("minefield-five-sectors")}else StarcadeHost.finish(score)}
  function open(){if(state==="lost"){reset();return}if(state==="won"){sector++;blank();return}const d=cells[cursor];if(d.flag)return;if(first)generate(cursor);if(d.mine){cells.forEach(v=>{if(v.mine)v.open=true});finish("lost")}else{reveal(cursor);if(complete())finish("won")}draw()}
  function flag(){if(state!=="play")return;const d=cells[cursor];if(!d.open)d.flag=!d.flag;draw()}
  function chord(){if(state!=="play")return;const d=cells[cursor];if(!d.open||!d.n)return;const around=neighbors(cursor);if(around.filter(i=>cells[i].flag).length!==d.n)return;for(const i of around){if(cells[i].flag||cells[i].open)continue;if(cells[i].mine){cells.forEach(v=>{if(v.mine)v.open=true});finish("lost");break}reveal(i)}if(state==="play"&&complete())finish("won");draw()}
  function draw(){if(state==="play")elapsed=performance.now()-started;x.fillStyle="#070c0b";x.fillRect(0,0,660,660);cells.forEach((d,i)=>{const q=i%N,r=i>>3,px=O+q*S,py=O+r*S;x.fillStyle=d.open?(d.mine?"#b84d4d":"#1d302c"):d.flag?"#3a3150":"#111d1a";x.fillRect(px,py,S-6,S-6);x.strokeStyle=i===cursor?"#fff":"#354b46";x.lineWidth=i===cursor?3:1;x.strokeRect(px,py,S-6,S-6);x.textAlign="center";x.textBaseline="middle";x.font="bold 25px Arial";if(d.flag&&!d.open){x.fillStyle="#c58cff";x.fillText("⚑",px+33,py+33)}else if(d.open&&(d.mine||d.n)){x.fillStyle=d.mine?"#fff":["","#8df7c7","#7dc7ff","#f2c879","#ff9fc8"][Math.min(4,d.n)];x.fillText(d.mine?"×":d.n,px+33,py+33)}});x.textBaseline="alphabetic";x.textAlign="left";x.font="14px Arial";x.fillStyle="#a9bbb7";x.fillText(`SECTOR ${sector}  MINES ${Math.min(18,8+sector*2)}  FLAGS ${cells.filter(d=>d.flag).length}  TIME ${Math.floor(elapsed/1000)}  SCORE ${score}`,O,28);if(state!=="play"){x.fillStyle="rgba(3,7,6,.88)";x.fillRect(0,278,660,110);x.textAlign="center";x.fillStyle=state==="won"?"#8df7c7":"#ff8d72";x.font="26px Arial";x.fillText(state==="won"?`SECTOR ${sector} CLEARED`:"MINE DETONATED",330,320);x.font="14px Arial";x.fillText(state==="won"?"A / ENTER: NEXT SECTOR":"A / ENTER: RESTART OPERATION",330,353)}}
  addEventListener("keydown",e=>{const k=StarcadeInput.key(e),q=cursor%N,r=cursor>>3;if(k==="ArrowLeft")cursor=r*N+(q+7)%N;if(k==="ArrowRight")cursor=r*N+(q+1)%N;if(k==="ArrowUp")cursor=((r+7)%N)*N+q;if(k==="ArrowDown")cursor=((r+1)%N)*N+q;if(k==="Action")open();if(k.toLowerCase()==="x")flag();if(k.toLowerCase()==="c")chord();if(StarcadeInput.isControl(k)||k.toLowerCase()==="x"||k.toLowerCase()==="c"){e.preventDefault();draw()}});
  reset();StarcadeHost.ready({title:"Minefield Protocol"});setInterval(()=>{if(state==="play")draw()},500);
})();
