"use strict";
(()=>{
  const balance=document.querySelector("#balance"),cards=document.querySelector("#cards"),oddsLine=document.querySelector("#odds"),status=document.querySelector("#status"),wager=document.querySelector("#wager"),cash=document.querySelector("#cash"),buttons=[...document.querySelectorAll("[data-bet]")];
  const suits=["♠","♥","♦","♣"],draw=()=>({rank:2+Math.floor(Math.random()*13),suit:suits[Math.floor(Math.random()*4)]});
  let current=draw(),active=false,busy=false,stake=0,mult=1,streak=0;
  const rank=n=>n<11?String(n):["J","Q","K","A"][n-11];
  const chance=choice=>choice==="high"?(14-current.rank)/12:(current.rank-2)/12;
  const show=()=>{balance.textContent=`CREDITS: ${CasinoBank.balance??"---"}`;const red=current.suit==="♥"||current.suit==="♦",face=rank(current.rank);cards.innerHTML=`<div class="card-deck"></div><div class="highlow-card${red?" red":""}"><span class="card-corner">${face}<br>${current.suit}</span><span class="card-pip">${current.suit}</span><span class="card-corner bottom">${face}<br>${current.suit}</span></div>`;oddsLine.textContent=`LOWER ${Math.round(chance("low")*100)}% · HIGHER ${Math.round(chance("high")*100)}%`;cash.disabled=!active;wager.disabled=active;buttons.forEach(b=>b.disabled=busy||(b.dataset.bet==="high"&&current.rank===14)||(b.dataset.bet==="low"&&current.rank===2))};
  async function choose(choice){if(busy)return;busy=true;buttons.forEach(b=>b.disabled=true);try{if(!active){stake=Number(wager.value);await CasinoBank.wager(stake);active=true;mult=1;streak=0}let next;do next=draw();while(next.rank===current.rank);const win=choice==="high"?next.rank>current.rank:next.rank<current.rank,odds=Math.max(1/13,chance(choice));current=next;if(win){streak++;mult=Math.min(20,mult*Math.max(1.08,.94/odds));status.textContent=`CORRECT · STREAK ${streak} · CASH OUT ${Math.floor(stake*mult)} CREDITS`;if(streak>=8)StarcadeHost.achievement("high-low-eight-streak")}else{await CasinoBank.payout(0);status.textContent=`WRONG · ${rank(next.rank)}${next.suit} BREAKS THE RUN`;StarcadeHost.finish(0);active=false;stake=0;mult=1;streak=0;show()}}catch(e){status.textContent=e.message;active=false;stake=0}finally{busy=false;show()}}
  async function cashout(){if(!active||busy)return;busy=true;try{const award=Math.floor(stake*mult),score=Math.max(0,award-stake);await CasinoBank.payout(award);status.textContent=`RUN CASHED OUT · ${award} CREDITS`;StarcadeHost.score(score);StarcadeHost.finish(score);active=false;stake=0;mult=1;streak=0;show()}catch(e){status.textContent=e.message}finally{busy=false}}
  buttons.forEach(b=>b.onclick=()=>choose(b.dataset.bet));cash.onclick=cashout;addEventListener("keydown",e=>{const key=StarcadeInput.key(e);if(key==="Left"){e.preventDefault();choose("low")}else if(key==="Right"||key==="Action"){e.preventDefault();choose("high")}});addEventListener("pagehide",()=>{if(active)CasinoBank.cancel().catch(()=>{})});CasinoBank.refresh().then(show).catch(e=>status.textContent=e.message);StarcadeHost.ready({title:"Celestial High / Low"});
})();
