"use strict";
(()=>{
  const order=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
  const red=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
  const canvas=document.querySelector("#rouletteCanvas"),ctx=canvas.getContext("2d"),balance=document.querySelector("#balance"),result=document.querySelector("#result"),status=document.querySelector("#status"),bet=document.querySelector("#bet"),number=document.querySelector("#number"),wager=document.querySelector("#wager"),play=document.querySelector("#play");
  let busy=false,wheelAngle=0,ballAngle=-Math.PI/2,ballRadius=238;
  const TAU=Math.PI*2,step=TAU/order.length,cx=canvas.width/2,cy=canvas.height/2;
  const show=()=>balance.textContent=`CREDITS: ${CasinoBank.balance??"---"}`,color=n=>n===0?"GREEN":red.has(n)?"RED":"BLACK";
  function ring(radius,width,stroke){ctx.beginPath();ctx.arc(cx,cy,radius,0,TAU);ctx.lineWidth=width;ctx.strokeStyle=stroke;ctx.stroke()}
  function draw(angle=wheelAngle,orb=ballAngle,radius=ballRadius){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();const brass=ctx.createRadialGradient(cx-75,cy-90,30,cx,cy,275);brass.addColorStop(0,"#f1d48b");brass.addColorStop(.35,"#8d642d");brass.addColorStop(.78,"#382516");brass.addColorStop(1,"#090d0c");ctx.fillStyle=brass;ctx.beginPath();ctx.arc(cx,cy,272,0,TAU);ctx.fill();ring(253,12,"#d7b66a");ring(233,5,"#342317");for(let i=0;i<order.length;i++){const start=-Math.PI/2+i*step+angle,end=start+step,n=order[i];ctx.beginPath();ctx.arc(cx,cy,226,start,end);ctx.arc(cx,cy,157,end,start,true);ctx.closePath();ctx.fillStyle=n===0?"#147352":red.has(n)?"#a83238":"#101618";ctx.fill();ctx.strokeStyle="#d5b466";ctx.lineWidth=1.5;ctx.stroke();const mid=start+step/2;ctx.save();ctx.translate(cx+Math.cos(mid)*192,cy+Math.sin(mid)*192);ctx.rotate(mid+Math.PI/2);ctx.fillStyle="#f5eee0";ctx.font="bold 16px Arial";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(n,0,0);ctx.restore()}const bowl=ctx.createRadialGradient(cx-35,cy-45,12,cx,cy,155);bowl.addColorStop(0,"#31564b");bowl.addColorStop(.55,"#0b2a22");bowl.addColorStop(1,"#020b09");ctx.fillStyle=bowl;ctx.beginPath();ctx.arc(cx,cy,153,0,TAU);ctx.fill();ring(152,6,"#cfad62");ring(107,4,"#8b6b36");ctx.fillStyle="#caa860";ctx.beginPath();ctx.arc(cx,cy,42,0,TAU);ctx.fill();ctx.fillStyle="#102a24";ctx.beginPath();ctx.arc(cx,cy,30,0,TAU);ctx.fill();ctx.fillStyle="#e4c676";for(let i=0;i<4;i++){ctx.save();ctx.translate(cx,cy);ctx.rotate(i*Math.PI/2);ctx.fillRect(-5,-102,10,72);ctx.restore()}ctx.beginPath();ctx.arc(cx,cy,15,0,TAU);ctx.fill();const bx=cx+Math.cos(orb)*radius,by=cy+Math.sin(orb)*radius;ctx.shadowColor="#fff";ctx.shadowBlur=12;ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(bx,by,8,0,TAU);ctx.fill();ctx.restore()}
  function payoutFor(n){const v=bet.value;if(v==="straight")return n===Number(number.value)?36:0;if(v.startsWith("dozen")){const d=Number(v.slice(-1));return n>=1+(d-1)*12&&n<=d*12?3:0}if(n===0)return 0;if(v==="red"||v==="black")return color(n)===v.toUpperCase()?2:0;if(v==="even")return n%2===0?2:0;if(v==="odd")return n%2?2:0;if(v==="low")return n<=18?2:0;if(v==="high")return n>=19?2:0;return 0}
  function animate(winner){return new Promise(resolve=>{const began=performance.now(),duration=2100,startWheel=wheelAngle,startBall=ballAngle,targetWheel=startWheel+TAU*3.25,targetIndex=order.indexOf(winner),targetBall=targetWheel-Math.PI/2+(targetIndex+.5)*step;function frame(now){const t=Math.min(1,(now-began)/duration),ease=1-Math.pow(1-t,4);wheelAngle=startWheel+(targetWheel-startWheel)*ease;const freeBall=startBall-TAU*5.4*ease;ballAngle=freeBall*(1-ease)+targetBall*ease;ballRadius=238-55*Math.pow(t,3);draw();if(t<1)requestAnimationFrame(frame);else{wheelAngle=targetWheel%TAU;ballAngle=targetBall%TAU;ballRadius=183;draw();resolve()}}requestAnimationFrame(frame)})}
  async function spin(){if(busy)return;busy=true;play.disabled=true;try{const stake=Number(wager.value);await CasinoBank.wager(stake);status.textContent="WHEEL IN MOTION";const n=Math.floor(Math.random()*37);await animate(n);result.textContent=`${n} · ${color(n)}`;result.dataset.color=color(n).toLowerCase();const mult=payoutFor(n),score=Math.max(0,stake*(mult-1));await CasinoBank.payout(stake*mult);status.textContent=mult?`WIN ${stake*mult} CREDITS · ${mult}x RETURN`:"NO WIN · PLACE ANOTHER BET";StarcadeHost.score(score);StarcadeHost.finish(score);show()}catch(e){status.textContent=e.message}finally{busy=false;play.disabled=false}}
  bet.onchange=()=>number.hidden=bet.value!=="straight";play.onclick=spin;addEventListener("keydown",e=>{if(StarcadeInput.key(e)==="Action"){e.preventDefault();spin()}});draw();CasinoBank.refresh().then(show).catch(e=>status.textContent=e.message);StarcadeHost.ready({title:"Orbital Roulette"});
})();
